### ISSUE TITLE
Add Dependabot to repository

### ISSUE THREAD

**Issue by adamelliotfields** [adamelliotfields/github-sandbox#2]
Use the following config:

```yaml
version: 1

update_configs:
  - package_manager: javascript
    directory: '/'
    update_schedule: weekly

default_reviewers:
  - adamelliotfields

default_labels:
  - dependabot

```
